default: &default
  adapter: postgresql
  host: localhost
  username: postgres  
  password: 59621020
  database: moat_db
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: moat_db

production:
  <<: *default
