import type { Metadata } from "next";
import { Radio_Canada } from "next/font/google";
import "./globals.css";

const mainFont =  Radio_Canada({ 
  subsets: ["latin"],
  weight: ['400', '500' ,'600', '700'],
  variable: '--font-family'
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={mainFont.variable}>
      <body>{children}</body>
    </html>
  );
}
